### PR TITLE
Update 100-JavaAppsLab.md

### PR DESCRIPTION
**Pull request by cholho**
@choichi 
- Added “in the Access Document” in the end of line of ‘<https://github.com/APACTestDrive/CloudNative_Mobile/compare/master...cholho-javaapps-100?quick_pull=1#diff-92bfd4b64d3d53fd1aa1fbdca168dbd7L11>' 
- Need to provide credentials for WebLogic.  We can put it in the access document, and give direction like “Please see Access Document for weblogic credentials.”
- How about adding some information on what participants are doing from the perspective of loyalty management. For example, we may add some information after Prerequisites as below:
### Accomplishment ###
- Through this lab, you will have a chance to create a DB connectivity between Java Application on JCS (Java Cloud Service) and DBMS on DB Cloud Service for loyalty management. (Sorry for my poor description here. I just give more information to participants because I’d like to make sure they are not lost.)

### CODE REVIEW

**Comment by heungheung** [comment]
@cholho I think this is a pull request. 
- ltem-1, I'm ok with the change
- Item-2, weblogic credential already update in master, step 5. I didn't see any additional change required
- Item-3, If you want to propose a change, please log an issue and assign someone to do the change. If you want to make to change yourself, please update the file and submit another pull-request, suggest you keep the same branch.

**Comment by cholho** [comment]
@heungheung 
Thanks for your feedback.^^
For item 3, I think Chris will have the description. I just want to give some example. Next time, I'm going to use issue for those things.

**Comment by heungheung** [comment]
@cholho  we are practicing AppDev 😸

**Comment by heungheung** [comment]
assign @cholho to commit and perform the actual merge

**Pull request merged**
