### PR TITLE
Update 101-JavaAppsLab.md

### PR DESCRIPTION
**Pull request by cholho**
@choichi 
- In addition to the introduction of DevCS, how about adding some information on what participants are doing from the perspective of loyalty management? For example, we may add some information after Prerequisites as below in the line of '<https://github.com/APACTestDrive/CloudNative_Mobile/compare/master...cholho-javaapps-101?quick_pull=1#diff-549f9b9ac4be5bf5a334f13e9c780309R31>'. 
Please make the description sexy~^:

For other comments, please refer to the attache doc. --> [JCS_Dry Run_JavaApps-101_cholho_feedback.docx](https://github.com/APACTestDrive/CloudNative_Mobile/files/1137991/JCS_Dry.Run_JavaApps-101_cholho_feedback.docx)

### CODE REVIEW

**Comment by heungheung** [comment]
I'm ok with the pull-request and it only change one file. For additional changes required, please open an issue and assign the corresponding author.

**Comment by cholho** [comment]
Got it :+1:

**Comment by heungheung** [comment]
assign @cholho to commit the actual merge... 😄  press the [Merge pull request] button.

**Comment by choichi** [comment]
@cholho 
Are you referring to master branch or the JavaAppsLab-delta-only branch?

I am making all my changes into it

**Comment by cholho** [comment]
@choichi
I am referring java apps~

**Comment by cholho** [comment]
@choichi,
Oops, I mean master one^^

**Comment by choichi** [comment]
Updated and commit into 'JavaAppsLab-delta-only', merge into 'master' later when all your comments & changes done in JavaAppsLab

@cholho Please put as an new 'Issue' for me to easier follow up, thanks

**Comment by cholho** [comment]
@choichi 
Great thanks, Chris^^

**Review by heungheung — CHANGES_REQUESTED** [review]
I will discourage to use **Accomplishment** unless you are putting something at the **end** of the lab. **Accomplishment** is about what you **have done**. 

If you want to say something about what **to expect**, **will learn** or **will do**, please just put in as part of **Objective**

**Comment by cholho** [comment]
@heungheung, choichi

Agree. Let's put it in the part of objective.

**Comment by heungheung** [comment]
@cholho for the time being, you are the assignee. If you want @choichi to make the change, please assign to Chris. Otherwise, I'll assume you will update the file in this merge request.

**Comment by choichi** [comment]
@cholho @heungheung 
Exactly... coz til now I work on the 'delta-only' branch, not this branch... until you assign to me specifically

**Comment by cholho** [comment]
@choichi @heungheung 
Hi Chris and Kenneth,
I put a change in the JavaApps Lab -101 in the branch. ("cholho-javaapps-101"). [https://github.com/APACTestDrive/CloudNative_Mobile/blob/cholho-javaapps-101/Java%20Apps/101-JavaAppsLab.md](url)
I noticed that other comments has been reflected in the branch ("JavaAppsLab-delta-only) by Chris. So I added a section called "About the Exercise Today". Please review and merge it.

**Comment by heungheung** [comment]
@choichi just in case you are look at this request - please hold.... I have additional comments / change request.

**Comment by choichi** [comment]
@heungheung 
Noted and on-hold....indeed working on the shell script for WLS til now

**Review by heungheung — CHANGES_REQUESTED** [review]
@cholho Sorry brother, I have quite a lot of comments

- Line 23-25, you already states `this tutorial demonstrate how to...`, then you have another section of `About the Exercise` -that actually superseded 23-25. **recommend you remove 23-25**
- Line 31-32, incorrect format. Please try preview and you will see the two lines/points actually join together. Please either add tailing space at line 31 or add extra CRLF
- Line 32, we used **we** in the previous sections, now this becomes **you**, you might want to try something like `we will get an idea of how we can...`

I will put ONE additional comment entry on my actual proposal.

**Comment by heungheung** [comment]
@cholho , here is my suggestion (BTW, I'm not sure if you want to say `future` or `further` use in the last line).

Starting from Line 23... something like

#### About the Exercise Today ####
 
In this exercise, we will
+ create a new `Developer Cloud Service Project` for the Loyalty Management System 
+ create a new `Developer Cloud Service Git Repository` to store the Loyalty Management Java Application Source Code
+ clone an external Git repository, which is stored in Github, to the `Developer Cloud Service Git Repository` create above.

So we will get an idea of how we can easily re-use a base code for extension and future uses.

**Comment by cholho** [comment]
@heungheung @choichi 
Thanks, Kenneth. I accepted your suggestion with typo correction.

**Comment by cholho** [comment]
@choichi 
Chris, I reflected Kenneth's suggestion with typo correction. Please review to merge it.

**Review by choichi — APPROVED** [review]

**Review by choichi — CHANGES_REQUESTED** [review]
Confirm if you want to put "further" uses or "future" use (as per Kenneth commented)

**Comment by heungheung** [comment]
:sob: anyway, still got problem about CRLF..... go ahead for the merge.... I'll do a direct commit later

**Review by heungheung — APPROVED** [review]

**Comment by choichi** [comment]
Ok merge 1st...

**Review by choichi — APPROVED** [review]

**Comment by heungheung** [comment]
finally...... :clap:

**Comment by choichi** [comment]
*ps, it seems I am still not familiar with the GitHub UI comment layout... sometimes got confused / mess up

**Comment by cholho** [comment]
@heungheung @choichi 
Thanks for your patience and efforts. :laughing:

**Pull request merged**
