### PR TITLE
Java apps lab delta only

### PR DESCRIPTION
**Pull request by choichi**
Completion of VirtualBox installation and usage guide

### CODE REVIEW

**Review by heungheung — APPROVED** [review]
Looks like cholho is busy with the Mobile part. I've taken a quick look and I'm ok with the changes. The changes actually only affect the VM instructions and there is no conflict with all other files.

**Comment by heungheung** [comment]
@choichi I suggest you can go ahead with the merge without waiting for cholho

**Review by cholho — APPROVED** [review]
@heungheung @choichi 
Hi all,
Oh, sorry. I missed this one.
Thanks for your notification, Kenneth. :+1: 
BTW, I'd like to get your suggestion on where we need to put images.
Regards,
CholHo.

**Comment by heungheung** [comment]
@cholho you mean images in mobile app? if yes, either discuss in email or start another issue for discussion.

**Pull request merged**
