### PR TITLE
Mobile lab delta

### PR DESCRIPTION
**Pull request by cholho**
@rayeswong @choichi @heungheung 
Hi All, 
Please review the mobile lab and let me have your comments on this.
For images, you can skip review them. :laughing: 

BTW, I think we need one and half hour for participants to finish this lab. 
I'd like to get your opinion on this, too.

Warm Regards,
CholHo.

### CODE REVIEW

**Comment by choichi** [comment]
@cholho 
Which MCS env I can make use to dry run? mcs-gse00011678-07?

Nvm, I already started with this account .... :)

**Review by heungheung — CHANGES_REQUESTED** [review]
request changes.... please see email for details.

**Comment by heungheung** [comment]
@cholho mine are more about typo / wordings instead of actual hands-on contents. You can also wait for Chris about the actual comments after running/testing the labs.

**Review by cholho — COMMENTED** [review]
@heungheung 
Hi Kenneth,
Thanks for you kind feedback.
I reflected your feedback based on your email.
Please let me have your approval on the changes I made. 
Regards,
CholHo.

**Comment by cholho** [comment]
@choichi @rayeswong 
Hi Chris and Rayes,
Including a RAML file, I reflected your reviews.
Please approve changes I made. If you approve them, I will merge them to make v1 of Mobile Lab.
Regards,
CholHo.

**Review by choichi — CHANGES_REQUESTED** [review]
Summary of changes sent by Email

**Review by heungheung — APPROVED** [review]
looks good to me for the time being.... In fact, we should have more review(s) even after merge.

**Comment by cholho** [comment]
@choichi @rayeswong 

We might need more refinement in next week.
BTW, if there are no big things to change, I'd like to get your approval on mobile lab. :laughing: 

Warm Regards,
CholHo.

**Review by choichi — APPROVED** [review]

**Pull request merged**
