### PR TITLE
Mobile lab short delta only

### PR DESCRIPTION
**Pull request by cholho**
@rayeswong @choichi

Hi Rayes & Chris,

I reflected SCC and Rayes work to make the mobile lab simplified.

In the mobile lab (404), we also put mobile app setting information to test push notification. 
It is duplicated part with 501 section of Putting All Together. So modified the 501 section to get rid of duplication lab contents.

Please take a look at them, and let me have your feedback.
Warm Regards,
CholHo.

### CODE REVIEW

**Comment by heungheung** [comment]
@cholho you are submitting a **MERGE REQUEST**. Are you proposing a **merge** or just request @choichi and @rayeswong to take a look. 

- if you really want a merge, I will recommend we should have at least 2 people run through (`dry run`) the lab before doing a merge
- if you just want ppl to **take a look** at this stage, please consider withdraw the merge request and create an issue only.

**Comment by cholho** [comment]
@heungheung 
Hi Kenneth,
Sorry for my poor expression.
I want Rayes and Chris to do dry-run.
So I will keep it as a pull request.

@rayeswong @choichi 
I know you are so busy, but please do dry-runs for this pull request.

Regards,
CholHo.

**Comment by cholho** [comment]
Hi Kenneth,Sorry for my poor expression.In fact, I want Rayes and Chris to do dry run for it.So I will keep it as a pull request.Hi Rayes and Chis,I know you are so busy, but please do the dru run for mobile part based on the above pull request.And lets finish it today.Regards,CholHo. 2017. 8. 10. 오후 10:56에 Kenneth Heung <notifications@github.com>님이 작성:@cholho you are submitting a MERGE REQUEST. Are you proposing a merge or just request @choichi and @rayeswong to take a look.
if you really want a merge, I will recommend we should have at least 2 people run through (dry run) the lab before doing a mergeif you just want ppl to take a look at this stage, please consider withdraw the merge request and create an issue only.

**Review by choichi — CHANGES_REQUESTED** [review]
@choichi, @rayeswong 

Short Lab 401:
-step 4: diagram doesn't match with description
-step 8: diagram doesn't match with description

(CholHo) In Lab 401, there is no step 8. Would you let me know which part you mentioned?
For step 4, it looks OK for me.

Short Lab 403: 
-"Unclear step number to reference": 
Possible download the wrong content of the raml file from GitHub UI, with those <html> tags included, need more detail how to download the raw file and save properly.
(CholHo) Corrected.

-Step 5: Duplicated description of - Adding response media type: Click on "Add Media Type"
(CholHo) Corrected.

-The whole section about "Implement the custom API for the Loyalty Management" is unclear, very confusing... 
(CholHo) Rayes, do you have any idea for this?

-Any missing import of json or raml? (package-TestDriveACCSCtdQRConnectorAPI.zip, package-TestDriveICSConnectorAPI.zip??) 
(CholHo) Two package files should be imported by ourselves before the CTD. They are in the "../common/assets/mobile" folder. We have to do that because of naming conflicts.

I got "There are unresolved dependencies in this uploaded implementation.
Expand the Dependencies section above to view the 3 unresolved entries and make the necessary corrections." after upload the "loyaltymanagementapi_1.0.zip" with updated package.json and loyaltymanagementapi.js
(CholHo) Corrected.

**Comment by choichi** [comment]
I cannot proceed further after on Lab 403, failed to import the .zip with "There are unresolved dependencies in this uploaded implementation.
Expand the Dependencies section above to view the 3 unresolved entries and make the necessary corrections."

@choichi 
Corrected~~
Regards,
CholHo.

**Comment by cholho** [comment]
@heungheung @choichi @rayeswong @kwanwan,

Looks we have a refined version.
I will merge this version.

Regards,
CholHo.

**Comment by heungheung** [comment]
@cholho  **have this change been tested?** 

**do we have anyone APPROVED / REVIEWED before this merge**

I will propose a roll-back!

**Comment by heungheung** [comment]
Can someone explain how does the mobile app get the details of the offer after receive the push?

**Comment by cholho** [comment]
@heungheung, @rayeswong,

Discussed it with Rayes.
We agreed to merge it this time for HK SCs to have dry-runs on the whole master branch.

Sorry for late notice on this.

Warm Regards,
CholHo.

**Review by heungheung — COMMENTED** [review]
These will not work. The offer info connector is missing in 402/403

**Pull request merged**
