### PR TITLE
Multiple update on 'Java apps lab delta only' into 'master'

### PR DESCRIPTION
**Pull request by choichi**
@cholho 
Better you review from this version onward, mutiple update on the assumption, background etc (no change on detail lab steps)
If any correction/add on lab steps, please fire me a new issue, then I will change and commit into delta branch here.

### CODE REVIEW

**Comment by heungheung** [comment]
@choichi @cholho 
1. I think you two need the get the above 2 conflict resolved. 
2. I have concerns..... why we need "About this tutorial **section**" - I DO think "**About this tutorial**" is enough. If we need **section** then.... it will become **Introduction Section**,  **Prerequisites Section**.

**Comment by choichi** [comment]
Removed 'section' and awaiting conflict to be resolved...

**Comment by cholho** [comment]
@choichi
I prefer to have introduction and Prerequisites section than tutorial one.

**Comment by choichi** [comment]
Updated all 'About this tutorial' header into 'Introduction'
Commit in delta branch, will raise a new pull request to merge with other major changes later

**Comment by heungheung** [comment]
@choichi @cholho  friendly reminder, still 1 conflict.... anyone will take up and resolve it?

**Comment by choichi** [comment]
Taking out Lab-100 soon (assume overall post-creation shell script works), with additional changes on Lab-101 too

**Comment by choichi** [comment]
@cholho @heungheung 
The 1 conflict resolved, please review and merge, thanks

**Review by cholho — APPROVED** [review]
@choichi @heungheung 
Thanks for your great work. :100:

**Pull request merged**
