### PR TITLE
Mobile lab short delta only

### PR DESCRIPTION
**Pull request by rayeswong**
Created a short version of the mobile lab. Please help to test and review before merging to master. You can find the MBE package for testing under "CloudNative_Mobile\common\assets\mobile\MBE Packages". Thanks!

### CODE REVIEW

**Review by heungheung — CHANGES_REQUESTED** [review]
looks good except... 401. 
10 - can be us2, em2 or em3
12 - can be us2, em2 or em3
change is not a must but if you have time, better make it less confused

**Comment by heungheung** [comment]
I don't have time to test. BTW, where are the packages files to be uploaded?

**Review by heungheung — APPROVED** [review]

**Comment by cholho** [comment]
@rayeswong 

Please refer to my comments as below:
(1) Android APK file
Need to replace the link for Android APK file in the prerequisites and replace the APK file in the ../common/mobile/assets/ folder.

(2) Package file
I assumed we are going to give participants MBE package file using thumb drive.  Is it correct?

(3) Lab 401
- Please search "successully" and replace it with "successfully"
- Please search "clieck" and replace it with "click"
- Please search "authorzied" and replace it with "authorized"

Others look good even though I can't go through all of lab without a package file.
Regards,
CholHo.

**Comment by rayeswong** [comment]
@cholho Thanks for the comments.

(1) Android APK file
This is strange. The mobile "Mobile lab short delta only" branch points to "master", but it looks the master branch has not updated. I did minor change to see if that can be changed.

(2) Package file
I've placed the example MBE package on "..\common\assets\mobile\MBE Packages" where you can get the package file and test.
I will generate all the 20 packages today and place those onto the same folder.
I assume we will give participants the MBE package file by using the thumb drive, same as the iar file in "integrations" lab.

(3) Lab 401
All are updated in the "Mobile lab short delta only" branch. I will create another pull request later today.

**Comment by heungheung** [comment]
There won't be 20 thumb drive. Be prepared participant need to download the files during the labs.

**Comment by heungheung** [comment]
Also. If you update the APK link within your branch and you also update the APK file itself. The change will be indicated in your branch and will be effective after the merge in master.

**Comment by heungheung** [comment]
I mean before the merge, the APK itself will NOT be available in master, but only in the branch.

That's why we are supposed to use relative links.

**Comment by cholho** [comment]
@rayeswong @heungheung @choichi 

FYI,
I will update the main image of introduction "[README.md](https://github.com/APACTestDrive/CloudNative_Mobile/tree/MobileLab-short-delta-only)" in this branch.

**Comment by heungheung** [comment]
@rayeswong the reason of the APK link problem. You've upload the APK to common/assets/mobile/Cafe_Supremo.apk but your link is point to ../common/assets/mobile/Cafe_Supremo.apk

**Comment by rayeswong** [comment]
@cholho @heungheung @choichi @kwanwan 
Done creating the MBE packages and uploaded onto
https://github.com/APACTestDrive/CloudNative_Mobile/tree/MobileLab-short-delta-only/common/assets/mobile/import/MBE%20Packages 

Whoever has time today, please help on testing.

Also we can have the India SCs to help testing.

**Comment by heungheung** [comment]
@rayeswong  wow.... this really change a lot.... so, they don't have to create MBC / Connector, only edit API..... the lab should be finished within an hour.... :smile:

**Pull request merged**
