### PR TITLE
Multiple update on 'Integrations lab delta only' into 'master'

### PR DESCRIPTION
**Pull request by choichi**
Match section title, name and format like in JavaAppsLab

### CODE REVIEW

**Comment by cholho** [comment]
@choichi 
Hi Chris, I'm trying to build mobile contents. (Still don't get information from SCC. :cry: )
I will try to see ICS part after I finishing mobile contents with dry-run.

BTW, let's talk about "Putting All Together" section next week.
Have a nice weekend.

Regards,
CholHo.

**Review by heungheung — APPROVED** [review]
Looks good to me.

**Comment by heungheung** [comment]
@cholho you are the assignee, please check and commit the merge.

**Comment by cholho** [comment]
@choichi 
Thansk for your good work on ICS. 
As we are agreed, let me  :ship: it.

**Review by cholho — APPROVED** [review]

**Pull request merged**
