### PR TITLE
add Git client install

### PR DESCRIPTION
**Pull request by heungheung**
For windows, git client is required

### CODE REVIEW

**Review by choichi — APPROVED** [review]
Just a minor comment: Would move the gitclient installation before bracket installation (line 54 - 56 @ README) better?

**Comment by heungheung** [comment]
I am neutral.... original what to do what you said but think some might actually already got GIT.... so... struggled for a while..... anyone want to vote?

**Comment by choichi** [comment]
Yes very minor and that's why I approved for merge. 
Not sure about Git popularity in India..... I vote for Git client installation 1st...

**Comment by rayeswong** [comment]
Just a quick thought, can we have this in another page, and only those people who don't have git installed should refer to a link that points to the guideline of git installation?

**Comment by heungheung** [comment]
@rayeswong please put it as issue..... Too much to be done in this instance and I will only treat what you suggested as enhancement :smile:

**Pull request merged**
